import asyncio
import sys
import os
import copy
from loguru import logger
from unittest.mock import patch

# Ensure backend is in path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../')))

# Force UTF-8 for Windows console
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

from app.engines.left_pupil.api_executor import APIExecutor
from app.schemas.api_ir import APIIR, ExecutionResult
from app.services.neural_design.graph import neural_design_graph
from app.core.config import settings

async def run_left_pupil_full_flow():
    print("=========================================================")
    print("🚀 ChongMing Full Flow E2E Test: Left Pupil (API) 🚀")
    print("=========================================================")
    
    if not settings.QWEN_API_KEY:
        logger.error("❌ QWEN_API_KEY is not set. Real model inference required.")
        return

    # ---------------------------------------------------------------------
    # Phase 1: Neural Design (Intent to API-IR)
    # ---------------------------------------------------------------------
    print("\n[Phase 1: Neural Design - Intent Extraction]")
    
    user_intent = "Call the dummyjson.com login API with valid credentials, then create a new product that includes special characters to test fuzzing."
    print(f"🗣️ User Intent: {user_intent}")
    
    # Init Neural Design Graph
    nd_graph = neural_design_graph
    
    # We will simulate the output of the Scenarist since a full RAG retrieval against DummyJSON
    # might require indexed Swagger docs which we don't assume are present in the test DB.
    # To keep this E2E reliable, we mock the final Node Scenarist output but run the actual API engine.
    print("🧠 Simulating Neural Design Scenarist Output (Bypassing Doc Retrieval)...")
    
    planned_irs = [
         APIIR(
            method="POST",
            url="https://dummyjson.com/auth/login",
            headers={"Content-Type": "application/json"},
            body={
                "username": "emilys",
                "password": "emilyspass",
                "expiresInMins": 30
            },
            assertions=[
                {"type": "status_code", "expected": 200},
                {"type": "jsonpath", "path": "$.accessToken", "operator": "exists"},
            ],
            extract={
                "jwt_token": "$.accessToken",
                "user_id": "$.id"
            }
        ),
        APIIR(
            method="POST",
            url="https://dummyjson.com/products/add",
            headers={
                "Content-Type": "application/json",
                "Authorization": "Bearer ${jwt_token}" 
            },
            body={
                "title": "Hack_Product_<script>alert(1)</script>",
                "description": "Generated by ChongMing Persona",
                "price": 99.99
            },
            assertions=[
                {"type": "status_code", "expected": 201},
            ],
            extract={
                "new_product_id": "$.id"
            }
        )
    ]
    
    # ---------------------------------------------------------------------
    # ---------------------------------------------------------------------
    # Phase 2: Engine Execution & Self-Healing (Left Pupil)
    # ---------------------------------------------------------------------
    print("\n[Phase 2: Left Pupil Execution & Auto-Healing]")
    
    os.environ["ENABLE_RED_TEAMER"] = "false"
    os.environ["ENABLE_JANITOR"] = "false"
    
    # Mock the Knowledge Base Search so the LLM doesn't crash if it tries to search Swagger Docs
    def mock_search_knowledge_base(query: str, project_id: str = "default") -> str:
        print(f"📚 [Mock] Tool Called: search_knowledge_base(query='{query}')")
        return "The correct API endpoint for creating a product is `/products/add`. There is no `add_malformed_url`."
        
    with patch('app.services.left_pupil.planner.search_knowledge_base', new=mock_search_knowledge_base):
        executor = APIExecutor(timeout=15.0)

        async with executor:
            # Login Step
            print(f"\n▶️ Executing Step 1: {planned_irs[0].method} {planned_irs[0].url}")
            res1 = await executor.execute(planned_irs[0])
            if not res1.success:
                print(f"❌ Login failed: {res1.error}")
                return
            executor.set_context("jwt_token", res1.extracted_values.get("jwt_token"))
            
            # Product Step
            print(f"\n▶️ Executing Step 2: {planned_irs[1].method} {planned_irs[1].url} (Expect Sabotage & Heal)")
            print("\n👿 [Test Harness] Sabotaging the request URL to force a 404 Error!")
            planned_irs[1].url = "https://dummyjson.com/products/add_malformed_url" # Sabotage URL to force 404
            
            # This should hit a 404 error, trigger Sherlock -> Healer -> Retry -> Success
            res2 = await executor.execute(planned_irs[1])
            
            print("\n=========================================================")
            if res2.success:
                print("✅ [Validation] Left Pupil successfully executed and Self-Healed!")
                print("   The sabotaged 404 was detected, healed (URL fixed or logic bypassed?), and passed.")
                print(f"   Final HTTP Status: {res2.response.status_code}")
            else:
                print("❌ [Validation] Left Pupil failed to heal the request.")
                print(f"   End Result: {res2.error}")
            print("=========================================================")

if __name__ == "__main__":
    asyncio.run(run_left_pupil_full_flow())
